/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.lang.management.ManagementFactory;
import java.lang.management.RuntimeMXBean;
import java.util.List;

public class App {
    public static void main(String[] args) {
        RuntimeMXBean runtimeMxBean = ManagementFactory.getRuntimeMXBean();
        List<String> jvmArguments = runtimeMxBean.getInputArguments();

        System.out.println("JVM Arguments:");
        for (String arg : jvmArguments) {
            System.out.println(arg);
        }

        if (!jvmArguments.contains("--sun-misc-unsafe-memory-access=deny")) {
            throw new RuntimeException("missing expected argument");
        }
    }
}
